package com.matthewgarrison.enums;

public enum TextureEnum {
	SPLASH_SCREEN, MAIN_MENU_SCREEN, MAIN_GAME_SCREEN, GAME_OVER_SCREEN, OPTIONS_SCREEN_EASY,
			OPTIONS_SCREEN_MEDIUM, OPTIONS_SCREEN_HARD, LEADERBOARDS_SCREEN, PAUSE_MENU, MAINGUY_RIGHT_1,
			MAINGUY_RIGHT_2, MAINGUY_RIGHT_3, MAINGUY_LEFT_1, MAINGUY_LEFT_2, MAINGUY_LEFT_3,
			MAINGUY_RIGHT_CROUCH, MAINGUY_LEFT_CROUCH, MAINGUY_RIGHT_JUMP, MAINGUY_LEFT_JUMP, PROJECTILE,
			POWERUP_EXTRA_LIFE, POWERUP_SCORE_MOD, POWERUP_JUMP_BOOST, ONSCREEN_LEFT_BUTTON,
			ONSCREEN_RIGHT_BUTTON, ONSCREEN_UP_BUTTON, ONSCREEN_DOWN_BUTTON, ONSCREEN_PAUSE_BUTTON,
			ONSCREEN_PLAY_BUTTON, EASY, EASY_SELECTED, MEDIUM, MEDIUM_SELECTED, HARD, HARD_SELECTED,
			NORMAL, NORMAL_SELECTED, SHEEP, SHEEP_SELECTED, GAME_START_UNPAUSE_3, GAME_START_UNPAUSE_2,
			GAME_START_UNPAUSE_1, GAME_START_UNPAUSE_GO;
}

